[package]
name = "stardust_derive"
version = "0.1.0"
edition = "2021"
workspace = ".."

[dependencies]
proc-macro2 = { version = "1.0" }
syn = { version = "2.0", features = ["full", "extra-traits"] }
quote = "1.0"
unicode-xid = "0.2"

[lib]
proc-macro = true
